### PR TITLE
Add images

### PR DESCRIPTION
**Pull request by yaacov**
@elad661 suggested using an image as a repo logo, this PR addes Images to the Art repo.

### CODE REVIEW

**Comment by elad661** [comment]
If we do end up using a picture for the organization logo, it should be a new one

**Comment by cben** [comment]
Let's see, what can we review here...
*Erez's smile is slightly obscured by Daniel, could you please re-take the picture?
Also, the second row of people should be indented by 80cm, this looks like ~60cm to me.*
LGTM :stuck_out_tongue_closed_eyes: 

For the historical record, this is not the whole team, not even at the moment photo was taken (2017-06-07), I think Federico and Scott missing because they're were not physically there.

**Comment by yaacov** [comment]
Will fix indentation and rebase :-)

**Comment by yaacov** [comment]
Eldan just sent the winning logo, not need to review this :-)

**Comment by yaacov** [comment]
Closing becouse of Eldans suggestion :-)

**Pull request closed without merging**
